# https://devenv.sh/integrations/github-actions/#complete-example
name: "Build and Release"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # pin@v26
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # pin@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

      - name: Run a single command in the devenv shell
        run: devenv shell hello
      - run: devenv shell release
      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # pin@v2
        if: startsWith(github.ref, 'refs/tags/') && runner.os == 'macOS'
        with:
          files: release.zip

# https://github.com/softprops/action-gh-release/blob/c7857c88c0b69847af67785971a0b5633c6d22cf/README.md?plain=1#L231-L236
permissions:
  contents: write
